# Development TOML configuration file for News Portal

[Database]
URL = "postgres://user:password@postgres:5432/news_portal?sslmode=disable"
MaxConns = 5
MaxConnsLifetime = "300s"

[App]
Host = "0.0.0.0"
Port = 3000